"""updated user

Revision ID: ac9ff2b34e0a
Revises: 8436c28e17d4
Create Date: 2026-04-02 15:11:12.144827

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac9ff2b34e0a'
down_revision: Union[str, Sequence[str], None] = '8436c28e17d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('skills', sa.String(), nullable=True))
    op.add_column('users', sa.Column('experience_level', sa.String(), nullable=True))
    op.add_column('users', sa.Column('desired_salary', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('about', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'about')
    op.drop_column('users', 'desired_salary')
    op.drop_column('users', 'experience_level')
    op.drop_column('users', 'skills')
    # ### end Alembic commands ###
